### ISSUE TITLE
Place install_wim_tweak

### ISSUE THREAD

**Issue by kenpc-git** [TheWorldOfPC/Windows11-Debloat-Privacy-Guide#1]
The Readme says to place it in C:Windows/System32, But the batch file is looking for it in C:Windows
Consider changing the Readme to reflect placing it there

**Comment by spesmynuts** [comment]
Well, not only in C:\Windows\System32 but on both folders if you didn't know. The World Of PC afaik informed the same thing in one of his Debloating Guides.
